// Mocks generated by Mockito 5.4.4 from annotations
// in edu_platform_demo/test/data/repository_implements/course_detail_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i2;
import 'package:edu_platform_demo/data/source/remote/course_remote_source.dart'
    as _i3;
import 'package:edu_platform_demo/data/source/remote/lecture_remote_source.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CourseRemoteSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCourseRemoteSource extends _i1.Mock
    implements _i3.CourseRemoteSource {
  @override
  _i4.Future<_i2.Response<Map<String, dynamic>>> getCourseList(
          {required Map<String, dynamic>? queryParameters}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCourseList,
          [],
          {#queryParameters: queryParameters},
        ),
        returnValue: _i4.Future<_i2.Response<Map<String, dynamic>>>.value(
            _FakeResponse_0<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getCourseList,
            [],
            {#queryParameters: queryParameters},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Response<Map<String, dynamic>>>.value(
                _FakeResponse_0<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getCourseList,
            [],
            {#queryParameters: queryParameters},
          ),
        )),
      ) as _i4.Future<_i2.Response<Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Response<Map<String, dynamic>>> getCourseDetail(
          {required String? courseId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCourseDetail,
          [],
          {#courseId: courseId},
        ),
        returnValue: _i4.Future<_i2.Response<Map<String, dynamic>>>.value(
            _FakeResponse_0<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getCourseDetail,
            [],
            {#courseId: courseId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Response<Map<String, dynamic>>>.value(
                _FakeResponse_0<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getCourseDetail,
            [],
            {#courseId: courseId},
          ),
        )),
      ) as _i4.Future<_i2.Response<Map<String, dynamic>>>);
}

/// A class which mocks [LectureRemoteSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLectureRemoteSource extends _i1.Mock
    implements _i5.LectureRemoteSource {
  @override
  _i4.Future<_i2.Response<Map<String, dynamic>>> getLectureList({
    required String? courseId,
    int? offset = 0,
    int? count = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLectureList,
          [],
          {
            #courseId: courseId,
            #offset: offset,
            #count: count,
          },
        ),
        returnValue: _i4.Future<_i2.Response<Map<String, dynamic>>>.value(
            _FakeResponse_0<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getLectureList,
            [],
            {
              #courseId: courseId,
              #offset: offset,
              #count: count,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Response<Map<String, dynamic>>>.value(
                _FakeResponse_0<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getLectureList,
            [],
            {
              #courseId: courseId,
              #offset: offset,
              #count: count,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<Map<String, dynamic>>>);
}
